#!/bin/bash

# directory with all the items in the stattus bar
ITEMS_DIR="$CONFIG_DIR/items"

# fonts
FONT='SF Pro'
NERD_FONT='JetBrainsMono Nerd Font'

bar=(
    height=40
    y_offset=5
    blur_radius=10
    position=top
    padding_left=5
    padding_right=5
    margin=5
    corner_radius=10
    color=0xE725273A
    shadow=on
    border_width=0
    border_color=0x44CAD3F5
)

defaults=(
  updates=when_shown
  icon.color=0xffCAD3F5
  icon.font="$FONT:Bold:16.0"
  icon.highlight_color=0xff728FCB
  icon.padding_left=3
  icon.padding_right=3
  label.color=0xffCAD3F5
  label.font="$FONT:Semibold:13.0"
  label.padding_left=3
  label.padding_right=3
  padding_right=2
  padding_left=2
  background.border_width=2
  background.corner_radius=5
  background.height=30
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

# # defaults
# sketchybar --default "${defaults[@]}"

# # add main bar
# sketchybar --bar "${bar[@]}"

# # source items to the bar
# source $ITEMS_DIR/logo.sh
# source $ITEMS_DIR/spaces.sh

# # watch for changes in the sketchybar directory
# sketchybar --hotload on

# # forcing all item scripts to run (never do this outside of sketchybarrc)
# sketchybar --update